apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment-demo-service

spec:
  replicas: 3

  selector:
    matchLabels:
      app: deployment-demo-service

  template:
    metadata:
      labels:
        app: deployment-demo-service

    spec:
      containers:
        - name: deployment-demo-service
          image: deployment-demo-service:ci
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: deployment-demo-config
                  key: APP_ENV

            - name: APP_REGION
              valueFrom:
                configMapKeyRef:
                  name: deployment-demo-config
                  key: APP_REGION

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: deployment-demo-secret
                  key: API_KEY